### ISSUE TITLE
Attempting to build dockerfile leads to following error 

### ISSUE THREAD

**Issue by seventinth** [manolitto/joplin-mail-gateway#11]
Running docker build leads to this error; can anyone diagnose the error?
```
Step 8/23 : RUN /home/node/.npm-global/bin/joplin config --import-file /home/node/joplin-config.json
 ---> Running in d47156b57ebc
/home/node/.npm-global/lib/node_modules/joplin/node_modules/@joplin/lib/models/Setting.js:902
            throw new Error(`Unknown key: ${key}`);
            ^

Error: Unknown key: config sync.5.username
    at Function.settingMetadata (/home/node/.npm-global/lib/node_modules/joplin/node_modules/@joplin/lib/models/Setting.js:902:19)
    at Function.formatValue (/home/node/.npm-global/lib/node_modules/joplin/node_modules/@joplin/lib/models/Setting.js:1116:25)
    at Function.setValue (/home/node/.npm-global/lib/node_modules/joplin/node_modules/@joplin/lib/models/Setting.js:1018:22)
    at Object.entries.forEach (/home/node/.npm-global/lib/node_modules/joplin/command-config.js:49:16)
    at Array.forEach (<anonymous>)
    at ReadStream.inputStream.on (/home/node/.npm-global/lib/node_modules/joplin/command-config.js:48:8)
    at ReadStream.emit (events.js:203:15)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
The related joplin-config.json is as such (edited from the repo direct)

```
{
  "dateFormat": "DD/MM/YYYY",
  "folders.sortOrder.field": "title",
  "layout.folderList.factor": 1,
  "layout.note.factor": 2,
  "layout.noteList.factor": 1,
  "locale": "en_GB",
  "notes.sortOrder.field": "user_updated_time",
  "notes.sortOrder.reverse": true,
  "revisionService.enabled": true,
  "revisionService.ttlDays": 90,
  "showCompletedTodos": true,
  "sync.8.url": "https://s3.amazonaws.com/",
  "sync.9.directory": "Apps/Joplin",
  "sync.interval": 300,
  "sync.maxConcurrentConnections": 5,
  "sync.target": 5,
  "sync.5.path": "https://notes.tld",
  "config sync.5.username": "user@protonmail.com",
  "config sync.5.password": "password",
  "sync.wipeOutFailSafe": true,
  "timeFormat": "HH:mm",
  "trackLocation": true,
  "uncompletedTodosOnTop": true
}

```

**Comment by manolitto** [comment]
@seventinth  please try to remove the "config" in these two lines:
"config sync.5.username": "user@protonmail.com",
"config sync.5.password": "password",

does this solve it?

**Comment by seventinth** [comment]
That does solve it. Thanks very much @manolitto ! 
On hindsight the error seems obvious. 

Cheers
